version: '3'
services:
  web:
    build: .
    ports:
     - "8000:8000"
    volumes:
      - ./:/opt/
    command: "python web/manage.py runserver 0.0.0.0:8000"

  test:
    build: .
    volumes:
      - ./:/opt/
    command: "python web/manage.py test web"
    stdin_open: true
    tty: true
