version: '3'
services:
  web:
    build: .
    ports:
     - "8000:8000"
    volumes:
      - ./:/opt/
    environment:
      - CACHE_HOST=cache-server

    command: "make run"
    depends_on:
      - cache-server

  cache-server:
    image: "redis:5.0.4-alpine"
    ports:
     - 6379:6379

  test:
    build:
      context: ./
      dockerfile: Dockerfile.test
    volumes:
      - ./:/opt/
    command: "make test"
    stdin_open: true
    tty: true

  lint:
    build:
      context: ./
      dockerfile: Dockerfile.test
    volumes:
      - ./:/opt/
    command: "make lint"
    stdin_open: true
